set (SOURCES
	stamina/Expressions.cpp
	stamina/Vector.cpp
	stamina/Matrix.cpp
	stamina/ProbMatrix.cpp
	stamina/OneCounterMatrix.cpp
	stamina/Monoid.cpp
	stamina/StabilisationMonoid.cpp
	stamina/MarkovMonoid.cpp
	stamina/MultiCounterMatrix.cpp
	stamina/VectorInt.cpp
	stamina/MultiMonoid.cpp
	stamina/Parser.cpp
	stamina/Automata.cpp
	stamina/StarHeight.cpp
	stamina/VectorUInt.cpp
	stamina/ExplicitAutomaton.cpp
	stamina/Output.cpp
	stamina/RegExp.cpp
	games/main.cpp
	games/parity.cpp
	games/wrapper.cpp
	games/games.cpp
	games/condition.cpp
	games/parser.cpp
	games/options.cpp
	games/tests.cpp
	games/iostuff.cpp
	games/output.cpp
	)

